name: anaconda-client-env-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}
channels:
  - conda-forge
  - defaults
dependencies:
  - anaconda-client
  - pip
  - pip:
      - -r requirements.txt